una promise ha 3 stati

pending -> sta lavorando

risolta -> il mio lavoro async Ã¨ stato completato correttamente senza problemi

rigettata -> chiamata http ha avuto un errore

se una promise viene rigettata, viene rigettato tutto il promise.all



PROMISE IN PARALLELO
const getProducts = async () => {
    const [product1, product2] =await Promise.all([
      axios.get('m,kkdsfffsaf'),
      axios.get('m,kkdsfffsaf')
    ])

    setProducts([product1, product2])
  }



GUARDARE ERROR BOUNDARY


applicativo il sui sodice sorgente gira sul browser viene generato client side

build -> prendo la dist -> metto su un server e il server serve i file statici


promise 
funzioni di funzioni
